# Copyright (c) 2026 pylov3d contributors.
# SPDX-License-Identifier: Apache-2.0
#
# Part of pylov3d, a Python/JAX port of LOV3D
# (https://github.com/mroviranavarro/LOV3D_multi, Apache-2.0).
# See LICENSE and NOTICE at the repository root.

"""Composite two-panel figure for the SSS proposal's Figure 3 (fig:ai).

Top: 1-D posterior marginals of the four Mars interior parameters from the
converged pocomc run (chain archived in docs/figures/proposal/
mars_posterior_chain.npz), with the deterministic point fit overlaid.

Bottom: hydration/serpentinization tidal sensitivity including both the
laboratory serpentinite-property bracket and mechanical-connectivity
uncertainty (Voigt, Hill, Reuss effective-medium limits). The preferred input
is the CSV generated by scripts/mars_serpentinite_connectivity_sensitivity.py.
If the CSV is absent, this script regenerates it before plotting.

The crust-shell lateral rigidity map that used to sit between these two panels
now lives with the Shadab infiltration map in fig:percolation
(fig_mars_rigidity_percolation.py).

Sized for a sidecaption figure at ~0.6\\linewidth (portrait-ish stack).
Output: --out (default: the SSS proposal repo's figures/fig3_composite.pdf).
"""

import argparse
import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from common import CATEGORICAL as COLORS, apply_style  # noqa: E402

REPO = Path(__file__).resolve().parents[2]
CHAIN = REPO / "docs" / "figures" / "proposal" / "mars_posterior_chain.npz"
CONNECTIVITY_CSV = REPO / "data" / "tests" / "mars" / "serpentinite_connectivity_sensitivity.csv"

LABELS = {
    "rho_core": r"$\rho_{\rm core}$ [kg m$^{-3}$]",
    "rho_lm": r"$\rho_{\rm lm}$ [kg m$^{-3}$]",
    "mu_scale": r"$\mu_{\rm scale}$",
    "R_core": r"$R_{\rm core}$ [km]",
}


def _load_or_generate_connectivity_rows(path: Path) -> list[dict]:
    if not path.exists():
        from mars_serpentinite_connectivity_sensitivity import run

        f_grid = [0.0, 0.1, 0.2, 0.3, 0.4, 0.5]
        rows = run(f_grid, nrbase=30)
        path.parent.mkdir(parents=True, exist_ok=True)
        with path.open("w", newline="") as fh:
            writer = csv.DictWriter(fh, fieldnames=list(rows[0]))
            writer.writeheader()
            writer.writerows(rows)
        return rows

    rows = []
    with path.open(newline="") as fh:
        for r in csv.DictReader(fh):
            rows.append({
                "scenario": r["scenario"],
                "law": r["law"],
                "f_h": float(r["f_h"]),
                "mu_eff_gpa": float(r["mu_eff_gpa"]),
                "K_eff_gpa": float(r["K_eff_gpa"]),
                "k2": float(r["k2"]),
                "delta_k2": float(r["delta_k2"]),
                "delta_k2_over_sigma": float(r["delta_k2_over_sigma"]),
                "sigma_required_1sigma": float(r["sigma_required_1sigma"]),
            })
    return rows


def main(out: Path) -> None:
    apply_style()
    d = np.load(CHAIN, allow_pickle=False)
    samples, point = d["samples"], d["point_fit"]
    names = [str(n) for n in d["free_params"]]

    fig = plt.figure(figsize=(4.6, 4.4))
    gs = fig.add_gridspec(2, 1, height_ratios=[1.0, 1.25], hspace=0.55)

    # --- Top: posterior marginals (1x4) -------------------------------
    gs_top = gs[0].subgridspec(1, 4, wspace=0.35)
    for i, name in enumerate(names):
        ax = fig.add_subplot(gs_top[0, i])
        ax.hist(samples[:, i], bins=28, color=COLORS[0], alpha=0.9)
        ax.axvline(point[i], color=COLORS[1], lw=1.4)
        ax.set_yticks([])
        ax.set_xlabel(LABELS.get(name, name), fontsize=7)
        ax.tick_params(labelsize=6)
        for s in ("top", "right", "left"):
            ax.spines[s].set_visible(False)
    fig.text(
        0.5, 0.985,
        f"Bayesian interior inference (pocomc): {samples.shape[0]} samples, "
        f"ESS={float(d['ess']):.0f}",
        ha="center", va="top", fontsize=8,
    )

    # --- Bottom: hydration-front Delta-k2 with connectivity -----------
    from pylov3d.mars_hydration import SIGMA_K2  # noqa: E402

    rows = _load_or_generate_connectivity_rows(CONNECTIVITY_CSV)
    rows = [r for r in rows if r["f_h"] <= 0.5 + 1e-12]
    f_vals = sorted({r["f_h"] for r in rows})

    def series(scenario: str, law: str) -> np.ndarray:
        by_f = {r["f_h"]: r["delta_k2"] for r in rows
                if r["scenario"] == scenario and r["law"] == law}
        return np.array([by_f[f] for f in f_vals], dtype=float)

    envelope = np.array([
        [r["delta_k2"] for r in rows if np.isclose(r["f_h"], f)]
        for f in f_vals
    ])
    env_lo = np.min(envelope, axis=1)
    env_hi = np.max(envelope, axis=1)

    central_voigt = series("central", "voigt")
    central_hill = series("central", "hill")
    central_reuss = series("central", "reuss")

    ax = fig.add_subplot(gs[1])
    ax.fill_between(
        f_vals, env_lo, env_hi, color=COLORS[0], alpha=0.18, linewidth=0,
        label="mineralogy + connectivity envelope",
    )
    ax.plot(f_vals, central_voigt, color=COLORS[0], lw=1.2, marker="o",
            markersize=2.4, label="central: Voigt")
    ax.plot(f_vals, central_hill, color=COLORS[1], lw=1.0, ls="--",
            label="central: Hill")
    ax.plot(f_vals, central_reuss, color=COLORS[2], lw=1.0, ls=":",
            label="central: Reuss")
    ax.axhline(SIGMA_K2, color="0.4", lw=0.9, ls="--")
    ax.annotate(
        r"current $1\sigma$ on observed $k_2$",
        xy=(f_vals[-1], SIGMA_K2), xytext=(-2, -3), textcoords="offset points",
        ha="right", va="top", fontsize=6, color="0.4",
    )
    ax.set_xlabel(r"hydrated ultramafic fraction $f_h$", fontsize=7)
    ax.set_ylabel(r"$\Delta k_2$", fontsize=7)
    ax.tick_params(labelsize=6)
    ax.set_title("Tidal sensitivity to hydration and mechanical connectivity", fontsize=8)
    ax.legend(loc="upper left", fontsize=5.6, frameon=False)
    for s in ("top", "right"):
        ax.spines[s].set_visible(False)

    fig.savefig(out, bbox_inches="tight")
    fig.savefig(out.with_suffix(".png"), dpi=300, bbox_inches="tight")
    print("wrote", out)
    print("connectivity input:", CONNECTIVITY_CSV)


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument(
        "--out",
        type=Path,
        default=Path("/Users/svance/SSS_2025_Mars/figures/fig3_composite.pdf"),
    )
    main(p.parse_args().out)
