#!/usr/bin/env python3
"""TASK-046 Gate B/C cross-check using each forcing's native coupling basis.

Each forcing is solved on the closure generated from its own (n,m), and the
resulting stress/strain fields are combined only at the energy-contraction
stage with ``get_energy_coupled_multibasis``.

Authoritative closure target
----------------------------
The original raw-grid MATLAB path in ``Consistency_test_Energy.m`` retains six
rheology modes and produces native active-mode counts [43, 41, 41] for forcing
m=[0,-2,+2]. The earlier coefficient-input path produced 125 modes per forcing
because Python scipy-SH coefficients were interpreted in MATLAB's different SH
coefficient convention before the nonlinear Maxwell transform. Those 125-mode
lateral k/energy numbers are retired and must not be used as a physical Gate C
anchor.

The uniform MATLAB Nrbase=50 anchor remains authoritative because it does not
involve lateral SH input:

    k_uni(2,m) = 0.7337217069 - 0.0151236751 i
    E_direct uniform = 2.1668778416
    E_Love   uniform = 2.2144024348

A new raw-grid lateral Gate C anchor is generated by
``scripts/io_matlab_raw_grid_energy_anchor.m``. Until those numbers are copied
into this driver, ``--assert-matlab`` checks the authoritative closure plus the
uniform response only; lateral response values are printed diagnostically.
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from pylov3d.couplings import get_couplings
from pylov3d.energy_multibasis import get_energy_coupled_multibasis
from pylov3d.grid import set_boundary_indices
from pylov3d.io_lateral import (
    build_io_forcings,
    build_io_model,
    io_default_numerics,
    io_mu_eta_variable,
)
from pylov3d.love import extract_love_numbers
from pylov3d.rheology import get_rheology, process_lateral_variations
from pylov3d.solver import get_solution

MATLAB_UNIFORM = {
    "k": 0.7337217069 - 0.0151236751j,
    "e_direct": 2.1668778416,
    "e_love": 2.2144024348,
}
TARGET_MODE_COUNTS = [43, 41, 41]


def love_energy_estimate(love_list, forcings) -> float:
    out = 0.0
    for fi in forcings:
        for j, fj in enumerate(forcings):
            love = love_list[j]
            idx = np.where((np.asarray(love.n) == fi.n) & (np.asarray(love.m) == fi.m))[0]
            if len(idx):
                out -= float(fi.F) * float(fj.F) * complex(love.k[idx[0]]).imag
    return out


def forcing_mode_k(love, forcing) -> complex:
    idx = np.where((np.asarray(love.n) == forcing.n) & (np.asarray(love.m) == forcing.m))[0]
    if not len(idx):
        raise RuntimeError(f"forcing mode ({forcing.n},{forcing.m}) missing from Love spectrum")
    return complex(love.k[idx[0]])


def monopole_direct_energy(
    results,
    forcings,
    model,
    numerics,
    n_s_list,
    m_s_list,
    *,
    couplings_list=None,
    lateral=None,
) -> float:
    """Return the physical positive monopole dissipation from GSH energy."""
    y_solutions = [(r[0], r[1], r[2]) for r in results]
    energy = get_energy_coupled_multibasis(
        y_solutions,
        forcings,
        model,
        numerics,
        n_s_list,
        m_s_list,
        Nenergy=numerics.Nenergy,
        couplings_list=couplings_list,
        lateral=lateral,
    )
    zero = np.where((np.asarray(energy.n) == 0) & (np.asarray(energy.m) == 0))[0]
    if not len(zero):
        raise RuntimeError("monopole energy term (0,0) missing")
    return float(energy.energy_integral[zero[0]])


def solve_uniform(raw_model, forcings, numerics):
    numerics, model = set_boundary_indices(numerics, raw_model)
    model = get_rheology(model, forcings)
    results = []
    for forcing in forcings:
        y, r, _Y, aprop = get_solution(model, forcing, numerics)
        love = extract_love_numbers(y, model, forcing)
        results.append((y, r, aprop, love))
    return model, numerics, results


def solve_lateral_native(raw_model, forcings, numerics, mu_variable, eta_variable):
    numerics, model = set_boundary_indices(numerics, raw_model)
    model = get_rheology(model, forcings)
    model, lateral = process_lateral_variations(
        model,
        forcings,
        mu_variable=mu_variable,
        eta_variable=eta_variable,
        rheology_cutoff=numerics.rheology_cutoff,
    )
    results = []
    couplings_list = []
    for forcing in forcings:
        couplings = get_couplings(
            lateral.variations,
            forcing.n,
            forcing.m,
            perturbation_order=numerics.perturbation_order,
        )
        y, r, _Y, aprop = get_solution(
            model, forcing, numerics, couplings=couplings, lateral=lateral,
        )
        love = extract_love_numbers(y, model, forcing, couplings=couplings)
        results.append((y, r, aprop, love))
        couplings_list.append(couplings)
    return model, numerics, lateral, couplings_list, results


def relerr(a, b) -> float:
    return abs(a - b) / max(abs(b), np.finfo(float).tiny)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--nrbase", type=int, default=10)
    parser.add_argument(
        "--assert-matlab",
        action="store_true",
        help=(
            "at Nrbase=50 assert raw-grid closure and uniform MATLAB parity; "
            "lateral k/energy stay diagnostic until the new raw-grid anchor is recorded"
        ),
    )
    args = parser.parse_args()

    t0 = time.perf_counter()
    raw_model = build_io_model()
    forcings = build_io_forcings()
    numerics = io_default_numerics(args.nrbase)
    mu_variable, eta_variable, _diagnostics = io_mu_eta_variable()

    model_u, num_u, uniform = solve_uniform(raw_model, forcings, numerics)
    model_l, num_l, lateral_rheology, couplings, lateral = solve_lateral_native(
        raw_model, forcings, numerics, mu_variable, eta_variable,
    )

    k_u = [forcing_mode_k(r[3], f) for r, f in zip(uniform, forcings)]
    k_l = [forcing_mode_k(r[3], f) for r, f in zip(lateral, forcings)]
    mode_counts = [len(c.n_s) for c in couplings]

    uniform_n_s = [np.asarray([f.n], dtype=int) for f in forcings]
    uniform_m_s = [np.asarray([f.m], dtype=int) for f in forcings]
    e_direct_u = monopole_direct_energy(
        uniform, forcings, model_u, num_u, uniform_n_s, uniform_m_s,
    )
    e_direct_l = monopole_direct_energy(
        lateral,
        forcings,
        model_l,
        num_l,
        [c.n_s for c in couplings],
        [c.m_s for c in couplings],
        couplings_list=couplings,
        lateral=lateral_rheology,
    )

    love_u = [r[3] for r in uniform]
    love_l = [r[3] for r in lateral]
    ek_u = love_energy_estimate(love_u, forcings)
    ek_l = love_energy_estimate(love_l, forcings)
    matlab_prefactor = 5.0 / float(model_u.Gg)
    e_love_u = matlab_prefactor * ek_u
    e_love_l = matlab_prefactor * ek_l
    mismatch_u = abs(e_direct_u - e_love_u) / abs(e_love_u)
    mismatch_l = abs(e_direct_l - e_love_l) / abs(e_love_l)

    print(f"TASK-046 Gate B/C, Nrbase={args.nrbase}")
    print(f"native lateral mode counts: {mode_counts} (raw-grid MATLAB target {TARGET_MODE_COUNTS})")
    for f, ku, kl in zip(forcings, k_u, k_l):
        print(
            f"forcing (n={f.n},m={f.m:+d})  "
            f"k_uni={ku.real:+.10f}{ku.imag:+.10f}i  "
            f"k_lat={kl.real:+.10f}{kl.imag:+.10f}i"
        )
    print(f"direct energy uniform/lateral: {e_direct_u:.10e}  {e_direct_l:.10e}")
    print(f"Love energy   uniform/lateral: {e_love_u:.10e}  {e_love_l:.10e}")
    print(f"direct/Love mismatch: uniform={100*mismatch_u:.4f}%  lateral={100*mismatch_l:.4f}%")
    print(f"wall time: {time.perf_counter()-t0:.1f} s")

    if args.nrbase == 50:
        print("\nAuthoritative uniform MATLAB comparison:")
        print(
            "  max relerr k_uni="
            f"{max(relerr(x, MATLAB_UNIFORM['k']) for x in k_u):.3e}"
        )
        print(
            "  relerr E_direct/E_love="
            f"{relerr(e_direct_u, MATLAB_UNIFORM['e_direct']):.3e}/"
            f"{relerr(e_love_u, MATLAB_UNIFORM['e_love']):.3e}"
        )
        print("  lateral k/energy: awaiting raw-grid MATLAB Gate C anchor")

        if args.assert_matlab:
            assert mode_counts == TARGET_MODE_COUNTS
            assert all(relerr(x, MATLAB_UNIFORM["k"]) < 1e-7 for x in k_u)
            assert relerr(e_direct_u, MATLAB_UNIFORM["e_direct"]) < 5e-3
            assert relerr(e_love_u, MATLAB_UNIFORM["e_love"]) < 5e-3
            assert mismatch_u < 0.03
            print("MATLAB closure + uniform assertions: PASS")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
